services:
  web:
    image: xraibackx/personal_assistant
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - ./.env.docker
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.docker

volumes:
  postgres_data: