services:
  # web:
  #   image: xraibackx/personal_assistant
  #   platform: linux/amd64
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./.env.docker
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:latest
    platform: linux/amd64
    container_name: "personal-assistant-database"
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: